config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end


    def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @books = Book.find(params[:id])
    @book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])    
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favorite_btn.html.erb
<%# 呼び出し元から 'book' オブジェクトを local 変数として受け取る想定 %>

<% if current_user.present? %>
  
  <%# book はパーシャルに渡された変数 %>
  <% if book.favorited_by?(current_user) %>
    <%# いいね済みの場合：塗りつぶしハート (fa-solid) と削除アクション %>
    <%= link_to book_favorite_path(book), method: :delete do %>
      <i class="fa-solid fa-heart" style="color: red;"></i>
      <%= book.favorites.count %>
    <% end %>
  <% else %>
    <%# いいね未済の場合：中抜きハート (fa-regular) と作成アクション %>
    <%= link_to book_favorite_path(book), method: :post do %>
      <i class="fa-regular fa-heart"></i>
      <%= book.favorites.count %>
    <% end %>
  <% end %>

<% else %>
  <%# ログインしていない場合: いいね数を表示するのみ %>
  <i class="fa-regular fa-heart"></i>
  <%= book.favorites.count %>
<% end %>

app/views/books/_list.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
      <label for="book_body">Opinion</label>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>
    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class='container'>
	<div class='row'>
	  <div class='col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto'>
	    <h1>Editing Book</h1>
      <% if @book.errors.any? %>
  	    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  		    <ul>
				    <% @book.errors.full_messages.each do |message| %>
					  <li><%= message %></li>
				    <% end %>
  		    </ul>
	    <% end %>
	    <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id), class: "book_3769" %> | <%= link_to "Back", books_path, class: "back" %>
	  </div>
	</div>
</div>

app/views/books/index.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class='container px-5 px-sm-0'>
	<% if @book.errors.any? %>
  	<h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
  		<ul>
				<% @book.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
  		</ul>
	<% end %>
	<div class='row'>
	  <div class='col-md-3'>
	    <h2>User info</h2>
	    <table class='table'>
	      <tr>
	        <%= image_tag @user.get_profile_image(100,100) %>
	      </tr>
	      <tr>
	        <th>name</th>
	        <th><%= @user.name %></th>
	      </tr>
	      <tr>
	        <th>introduction</th>
	        <th><%= @user.introduction %></th>
	      </tr>
	    </table>

	    <div class='row'>
        <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit user 4033" do %><i class="fas fa-user-cog"></i><% end %>
	    </div>

	    <%= render 'list', book: @book %>

	  </div>

	  <div class='col-md-8 offset-md-1'>
	    <h2>Books</h2>
	    <table class='table table-hover table-inverse'>
	      <thead>
	        <tr>
	          <th></th>
	          <th>Title</th>
	          <th>Opinion</th>
	          <th colspan="3"></th>
	        </tr>
	      </thead>
	      <tbody>
          <% @books.each do |book| %>
              <tr>
                <td>
									<%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %>
								</td>
                <td>
									<%= link_to book_path(book.id), class: "book_3766" do %><%= book.title %><% end %>
                <td><%= book.body %></td>
								<td>
                  <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorite_path(book), method: :delete do %>
                    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
                  <% end %>
                    <%= book.favorites.count %> 
                   <% else %>
                    <%= link_to book_favorite_path(book), method: :post do %>
                   <i class="far fa-heart" aria-hidden="true"></i>
                  <% end %>
                   <%= book.favorites.count %> 
                   <% end %>
                </td>
                <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
              </tr>
            <% end %>
        </tbody>
	    </table>
	  </div>
	</div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class='container'>
	<div class='row'>
	  <div class='col-md-3'>
	    <h2>User info</h2>
	    <table class='table'>
	      <tr>
	        <%= image_tag @books.user.get_profile_image(100,100) %>
	      </tr>
	      <tr>
	        <th>name</th>
	        <th><%= @books.user.name %></th>
	      </tr>
	      <tr>
	        <th>introduction</th>
	        <th><%= @books.user.introduction %></th>
	      </tr>
	    </table>

	    <div class='row'>
        <%= link_to edit_user_path(@books.user), class: "btn btn-outline-secondary btn-block edit user 4033" do %><i class="fas fa-user-cog"></i><% end %>
			</div>

	    <%= render 'list', book: @book %>

	  </div>

	  <div class='col-md-8 offset-md-1'>
	    <h2>Book detail</h2>
	    <table class='table'>
	      <tbody>
            <tr>
              <td>
                <%= link_to(user_path(@books.user.id)) do %><%= image_tag @books.user.get_profile_image(100,100) %><br><%= @books.user.name %><% end %>
              </td>
              <td>
                <%= link_to(book_path(@books.user.id)) do %><%= @books.title %><% end %>
              </td>
              <td><%= @books.body %></td>

            <%# #いいね機能 %>
            <td>
              <% if @books.favorited_by?(current_user) %>
                <%= link_to book_favorite_path(@books), method: :delete do %>
                  <i class="fa-solid fa-heart" style="color: red;"></i>
                  <%= @books.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorite_path(@books), method: :post do %>
                  <i class="fa-regular fa-heart"></i>
                  <%= @books.favorites.count %>
                <% end %>
              <% end %>
            </td>

            <% if @books.user == current_user %>
              <td><%= link_to 'Edit', edit_book_path(@books), class: "btn btn-sm btn-success edit_book_3769" %></td>
              <td><%= link_to 'Destroy', book_path(@books), class: "btn btn-sm btn-danger destroy_book_3769", method: :delete, data: { confirm: '本当に消しますか?' } %></td>
            <% end %>
            </tr>
        </tbody>
	    </table>

			<!-- コメント表示エリア -->
    <div id="comment-area" class="mt-4">
      <!-- コメント件数表示 -->
      <h4 class="mb-3">コメント件数：<%= @books.book_comments.count %>件</h4>

      <!-- コメント一覧 -->
      <% @books.book_comments.each do |book_comment| %>
        <div class="media mb-3 p-3 border rounded">
          <%= image_tag book_comment.user.get_profile_image(50, 50), class: "mr-3 rounded-circle" %>
          <div class="media-body">
            <!-- ユーザー名とコメント投稿日時 -->
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <%= link_to book_comment.user.name, user_path(book_comment.user), class: "font-weight-bold" %>
                <small class="text-muted ml-2"><%= book_comment.created_at.strftime('%Y/%m/%d') %></small>
              </div>
              <!-- コメント削除ボタン (投稿者のみ表示) -->
              <% if book_comment.user == current_user %>
                <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, data: { confirm: 'コメントを削除しますか?' }, class: "btn btn-danger btn-sm" %>
              <% end %>
            </div>
            <!-- コメント本文 -->
            <p class="mt-1 mb-0"><%= book_comment.comment %></p>
          </div>
        </div>
      <% end %>
    </div>

    <!-- コメント投稿フォームエリア -->
    <div class="mt-5">
      <h4 class="mb-3">コメントを投稿する</h4>
      <%= form_with model: [@books, @book_comment], local: true do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "form-control" %>
        </div>
        <%= f.submit "送信する", class: "btn btn-success" %>
      <% end %>
    </div>
	  </div>
	</div>
</div>

app/views/homes/about.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>

app/views/homes/top.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
       <a class="navbar-brand" href="/"><span>Bookers</span></a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class:"nav-link text-light" do%>
              	<i class="fa-solid fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class:"nav-link text-light" do%>
              	<i class="fa-solid fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class:"nav-link text-light" do%>
              	<i class="fa-solid fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do%>
              	<i class="fa-solid fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path, class:"nav-link text-light" do%>
              	<i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class:"nav-link text-light" do %>
              	<i class="fa-solid fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
              	<i class="fa-solid fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class:"nav-link text-light" do %>
              	<i class="fa-solid fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
          <% end %>
        </ul>
       </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Bookers2-Demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9532b50917.js"crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_list.html.erb
<h2>User info</h2>
	  <table class='table'>
	    <tr>
	      <%= image_tag @user.get_profile_image(100,100) %>
	    </tr>
	    <tr>
	      <th>name</th>
	      <th><%= @user.name %></th>
	    </tr>
	    <tr>
	      <th>introduction</th>
	      <th><%= @user.introduction %></th>
	    </tr>
	  </table>
		
		<div class='row'>
        <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit user 4033" do %><i class="fas fa-user-cog"></i><% end %>
	  </div>

	  <%= render 'books/list', book: @book %>

app/views/users/edit.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class='container'>
	<div class='row'>
	  <div class='col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto'>
	    <h2>User info</h2>
        <%= form_with model: @user do |f| %>
          <% if @user.errors.any? %>
            <div>
            <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
            </div>
          <% end %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name, class: "form-control name"%>
          </div>
          <div class="form-group">
            <label for="user_image">Image</label>
            <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file user_image" %>
          </div>
          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_field :introduction, class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
          </div>
        <% end %>
	  </div>
	</div>
</div>

app/views/users/index.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class='container px-5 px-sm-0'>
	<div class='row'>
		<div class='col-md-3'>

			<%= render 'list', user: @user %>

		</div>

	  <div class='col-md-8 offset-md-1'>
	    <h2>Users</h2>
	    <table class='table'>
	      <thead>
	        <tr>
	          <th>image</th>
	          <th>name</th>
	          <th colspan="3"></th>
	        </tr>
	      </thead>
	      <tbody>
          <% @users.each do |user| %>
              <tr>
                <td><%= image_tag user.get_profile_image(100,100) %></td>
                <td><%= user.name %></td>
                <td><%= link_to 'Show', user, class: "book_4030" %></td>
              </tr>
          <% end %>
        </tbody>
	    </table>
	  </div>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice">
  <%= flash[:notice] %>
</p>

<div class='container px-5 px-sm-0'>
	<div class='row'>
		<div class='col-md-3'>

			<%= render 'list', user: @user %>
		
		</div>

	  <div class='col-md-8 offset-md-1'>
	    <h2>Books</h2>
	    <table class='table table-hover table-inverse'>
	      <thead>
	        <tr>
	          <th></th>
	          <th>Title</th>
	          <th>Opinion</th>
	          <th colspan="3"></th>
	        </tr>
	      </thead>
	      <tbody>
					<% @books.each do |book| %>
              <tr>
                <td>
									<%= link_to user_path(book.user.id) do %><%= image_tag book.user.get_profile_image(100,100) %><% end %>
								</td>
                <td>
									<%= link_to book_path(book.id), class: "book_3769" do %><%= book.title %><% end %>
                <td><%= book.body %></td>
								<td id="favorite_btn_<%= book.id %>">
								  <%= render 'books/favorite_btn', book: book %>
								</td>
                <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
              </tr>
            <% end %>
        </tbody>
	    </table>
	  </div>
	</div>
</div>